version: '3.8'
services:
  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ASSIGN
    ports:
      - '3306:3306'
  redis-single-node-cluster:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    ports:
      - '6379:6379'
  # SNMP 시뮬레이터 추가
  snmp-simulator:
    image: tandrup/snmpsim
    ports:
      - "161:161/udp"
    volumes:
      - ./data:/usr/local/snmpsim/data
